accounts/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    
    path('', views.my_profile, name='my-profile'),
    path('register-user/', views.register_user, name='register-user'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('customer-dashboard/', views.customer_dashboard, name='customer-dashboard'),
    path('vendor-dashboard/', views.vendor_dashboard, name='vendor-dashboard'),
    path('my-profile/', views.my_profile, name='my-profile'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('email-verification/', TemplateView.as_view(template_name='accounts/user-confirmation.html'), name='email-verification'),
    path('forget-password/', views.forgot_password, name='forget-password'),
    path('reset-password/', views.reset_password, name='reset-password'),
    path('reset-password-validate/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('link-expire/', TemplateView.as_view(template_name='link-expire.html'), name='link-expire'),
    path('api/get-address/', views.get_address, name='get-address'),

    path('vendor/', include('vendor.urls'), name='vendor')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('menu-builder/', views.menu_builder, name="menu-builder"),
    path('menu-builder/category/<int:pk>/', views.fooditems_by_category, name="fooditems-by-category"),
    path('add-category/', views.add_category, name="add-category"),
    path('edit-category/<int:pk>/', views.edit_category, name="edit-category"),
    path('delete-category/<int:pk>/', views.delete_category, name="delete-category"),
    path('add-fooditem/<int:pk>/', views.add_fooditem, name="add-fooditem"),
    path('edit-fooditem/<int:pk>/', views.edit_fooditem, name="edit-fooditem"),
    path('delete-fooditem/<int:pk>/', views.delete_fooditem, name="delete-fooditem"),

    #opening hour crud
    path('opening-hour/', views.opening_hour, name="opening-hour"),
    path('add-opening-hour/', views.add_opening_hour, name="add-opening-hour"),
    path('edit-opening-hour/<int:pk>/', views.edit_opening_hour, name="edit-opening-hour"),
    path('delete-opening-hour/<int:pk>/', views.delete_opening_hour, name="delete-opening-hour"),

]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

multivendor/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('vendor/', include(('vendor.urls', 'vendor'), namespace='vendor')),
    path('menu/', include(('menu.urls', 'menu'), namespace='menu')),
    path('api/search/', views.search, name='api_search'),
    path('', include(('marketplace.urls', 'marketplace'), namespace='marketplace'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import FileExtensionValidator
from django.contrib.gis.geos import Point


class CustomManager(BaseUserManager):
    def create_user(self, email,  password=None, **extra_fields):
        
        if not email:
            raise ValueError('Email field cannot be empty')
        
        user = self.model(email = self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,password=None, **extra_fields):
        user = self.create_user(
            email = self.normalize_email(email),
            password=password,
            **extra_fields
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    VENDOR = 1
    CUSTOMER = 2
    ROLE_CHOICES = (
        (VENDOR, 'Vendor'),
        (CUSTOMER, 'Consumer')
    )
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=50, unique=True)
    phonenumber = models.CharField(max_length=12, blank=True, null=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)

    #required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomManager()

    class Meta:
        db_table = "customuser"

    def __str__(self):
        return str(self.email)
    
    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Vendor'
        if self.role == 2:
            user_role = 'Consumer'
        return user_role


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, related_name='userprofile', on_delete=models.CASCADE, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='users/profile_pictures', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png'])] ,blank=True, null=True)
    cover_picture = models.ImageField(upload_to='users/cover_picture', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png'])] ,blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=40, blank=True, null=True)
    state = models.CharField(max_length=40, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    pincode = models.CharField(max_length=6, blank=True, null=True)
    latitude = models.CharField(max_length=10, null=True, blank=True)
    longitude = models.CharField(max_length=10, null=True, blank=True)
    location = models.PointField(null=True, blank=True, srid=4326) 
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "user_profile"

    def __str__(self):
        return str(self.user)
    
    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))
            return super(UserProfile, self).save(*args, **kwargs)
    

accounts/forms.py
from django import forms
from .models import CustomUser


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = CustomUser
        fields = ['firstname', 'lastname', 'username', 'email']

    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        
        return cleaned_data
    

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegisterForm
from .models import CustomUser
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from .utils import detect_user, send_verification_email, send_password_reset_email
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.shortcuts import render, redirect
from .utils import get_reverse_geo_data
from vendor.models import OpeningHour, Vendor
from django.db.models import Case, When, IntegerField
from datetime import datetime



#restrict the customer from accessing user vendor page
def check_is_vendor(user):
    if not user.is_authenticated:
        return redirect('accounts:login')
    if user.role == 1:
        return True
    else:
        raise PermissionDenied

#restrict the vendor from accessing user customer page
def check_is_customer(user):
    if not user.is_authenticated:
        return redirect('accounts:login')
    if user.role == 2:
        return True
    else:
        raise PermissionDenied

# Create your views here.
def register_user(request):
    if request.user.is_authenticated:
        messages.info(request, 'You are already logged in!')
        return render(request, 'index.html')
    elif request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.role = CustomUser.CUSTOMER
            password = form.cleaned_data['password']
            user.set_password(password)
            form.save()
            send_verification_email(request, user)
            messages.success(request, "Your account has been registered successfully")
            return redirect('/accounts/email-verification/')
        return render(request ,'accounts/register-user.html', {'form':form})
    else:
        form = UserRegisterForm()
        return render(request ,'accounts/register-user.html', {'form':form})
    
def user_login(request):
    if request.user.is_authenticated:
        messages.info(request, 'You are already logged in!')
        return render(request, 'index.html')
    elif request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
    else:
        return render(request, 'accounts/login.html')
    messages.error(request, 'Invalid credentials')
    return render(request, 'accounts/login.html')

def user_logout(request):
    logout(request)
    return redirect('/')

@login_required
@user_passes_test(check_is_customer)
def customer_dashboard(request):
    return render(request, 'customer/customer-dashboard.html')


def vendor_dashboard(request):
    vendor = get_object_or_404(Vendor, user=request.user)
    
    # Get current day (0=Monday, 1=Tuesday, ..., 6=Sunday)
    current_day = datetime.now().weekday() + 1
    now = datetime.now()
    current_time = now.time()
    
    # Create a custom ordering that puts current day first
    opening_hours = OpeningHour.objects.filter(vendor=vendor).annotate(
        day_order=Case(
            When(day=current_day, then=0),
            default=1,
            output_field=IntegerField()
        )
    ).order_by('day_order', 'day', 'from_hour')

    # Default status
    status = "Closed"

     # Check if vendor is open now
    for slot in opening_hours:
        if slot.day == current_day and not slot.is_closed:
            # Convert from_hour and to_hour strings to time objects if they exist
            if slot.from_hour and slot.to_hour:
                time_format = "%I:%M %p"
                from_time = datetime.strptime(slot.from_hour, time_format).time()
                to_time = datetime.strptime(slot.to_hour, time_format).time()
                # Assuming from_hour and to_hour are in "HH:MM" format
                
                # Check if current time is within the opening hours
                if from_time <= current_time <= to_time:
                    status = "Open"
                    break 
                else:
                    status = "Closed"

    return render(request, 'vendor/vendor-dashboard.html', {
        'vendor': vendor,
        'opening_hours': opening_hours,
        'status': status
    })


@login_required
def my_profile(request):
    user = request.user
    redirectUrl = detect_user(user)
    return redirect(redirectUrl)

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = CustomUser._default_manager.get(pk=uid)
    except(TypeError, ValueError, CustomUser.DoesNotExist, OverflowError):
        user = None

    if user and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect("/accounts/login")
    
def forgot_password(request):
    if request.method == "POST":
        email =  request.POST.get('email')
        user = CustomUser.objects.filter(email = email).first()
        if user:
            send_password_reset_email(request, user)
            # return redirect('/')
        else:
            messages.error(request, 'Email doesnt exit')
            return render(request, "accounts/forgot-password.html")
    return render(request, "accounts/forgot-password.html")

def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = CustomUser._default_manager.get(pk=uid)
    except(TypeError, ValueError, CustomUser.DoesNotExist, OverflowError):
        user = None
    
    if user and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        return redirect('/accounts/reset-password')
    else:
        return redirect('/accounts/link-expire')

    # return render(request, "accounts/reset-password.html")

def reset_password(request):
    if request.method == "POST":
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        if password == confirm_password:
            pk = request.session.get('uid')
            user = CustomUser.objects.get(pk=pk)
            user.set_password(password)
            user.is_active=True
            user.save()
            return redirect('/accounts/login')
        else:
            messages.error(request, "Password mismatch")
            return render(request, "accounts/reset-password.html")
    
    return render(request, "accounts/reset-password.html")


#current location
@api_view(['GET'])
def get_address(request):
    try:
        lat = float(request.GET.get('lat'))
        lon = float(request.GET.get('lon'))
        addr = get_reverse_geo_data(lat, lon)
        return Response({'address': addr}, status=200)
    except Exception as e:
        return Response({'error': str(e)}, status=400)

templates/accounts/customer-dashboard.html
{% extends 'master/base.html' %}
{% load static %}

{% block content %}

<h4>Welcome {{user.username}}</h4>
<p>This is a {{user.get_role}}</p>
{% include 'alerts.html' %}

{% endblock %}

templates/accounts/forgot-password.html
{% extends 'master/base.html' %}
{% load static %}

{% block content %}

<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder" style="min-height: 374px;">
                        <div class="user-holder">
                            <h4 class="text-center" style="margin-bottom: 0;">Forgot your password?</h4>
                            <p class="text-center">please eneter your email address we will send you a link reset password.</p>
                    <hr>
                    <div id="restaurant-sets-holder">
                        <form class="form-fields-set foodbakery-dev-restaurant-form" method="post" action="{% url 'accounts:forget-password' %}">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                <ul>
                                                    <li>
                                                        <div class="">
                                                            <div class="field-holder">
                                                                <label>Email Address</label>
                                                               <input type="email" name="email">
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    {% include 'alerts.html' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Continue" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/login.html
{% extends 'master/base.html' %}
{% load static %}

{% block content %}

<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h4 class="text-center" style="margin-bottom: 0;">WELCOME BACK TO FOODONLINE</h4>
                            <p class="text-center">Please log in to access your account and manage your orders effortlessly.</p>
                    <hr>
                    <div id="restaurant-sets-holder">
                        <form class="form-fields-set foodbakery-dev-restaurant-form" method="post" action="/accounts/login/">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                <ul >
                                                    <li>
                                                        <div class="">
                                                            <div class="field-holder">
                                                                <label>Email Address</label>
                                                               <input type="email" name="email">
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="">
                                                            <div class="field-holder">
                                                                <label>Password</label>
                                                                <input type="password" name="password">

                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    {% include 'alerts.html' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Register" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                                <div class="text-end">
                                                    <a href="{% url 'accounts:forget-password' %}">Forget Password</a>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/register-user.html
{% extends 'master/base.html' %}
{% load static %}

{% block content %}

<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">WELCOME TO FOODONLINE</h4>
                    <p class="text-center">Please fill this form to get yourself onboarded in the foodOnline marketplace.</p>
                    <hr>
                    <div id="restaurant-sets-holder">
                        <form class="form-fields-set foodbakery-dev-restaurant-form" method="post" action="/accounts/register-user/">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                <ul >

                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>First name</label>
                                                                {{ form.firstname }}
                                                                <label for="">{{form.firstname.errors}}</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Last name</label>
                                                                {{ form.lastname }}
                                                                <label for="">{{form.lastname.errors}}</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>User Name </label>
                                                                {{ form.username }}
                                                                <label for="">{{form.username.errors}}</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Email Address</label>
                                                                {{ form.email }}
                                                                <label for="">{{form.email.errors}}</label>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    
                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Password</label>
                                                                {{ form.password }}
                                                                <label class="error " style=" color: red;">{{ form.non_field_errors }}</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Confirm Password</label>
                                                                {{ form.confirm_password }}
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    {% include 'alerts.html' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Register" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/user-confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Successful</title>
</head>
<body>
    <div style="text-align: center; margin-top: 50px;">
        <h1>Registration Successful!</h1>
        <p>
            A confirmation email has been sent to your email address. Please check your inbox (and spam/junk folder) and click on the link to activate your account.
        </p>
        <p>Thank you for registering!</p>
    </div>
</body>
</html>

templates/accounts/vendor-dashboard.html
{% extends 'master/base.html' %}
{% load static %}

{% block content %}

<h4>Welcome {{user.username}}</h4>
<p>This is a {{user.get_role}}</p>
{% include 'alerts.html' %}

{% endblock %}